server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: <Enter you URL here>

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - web
    labels:
      job: Web 
      __path__: /logs/server.log