global:
  scrape_interval: 60s
scrape_configs:
  - job_name: "sample express monitoring"
    static_configs:
      - targets: 
        - web:4500
remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: 604963
    password: <Your Grafana API Key>